apiVersion: v1
kind: Secret
metadata:
  name: my-github-ssh-key
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/Abdelaziz-Gbr/terraformAWS.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEA4hpQ0d5U+rvOMlQZIhRvBl4YgPm5e8SdAIlGvtXvIYwg0x97ITZ8
    RUxpJXHz7R43JbiSR0orvtGMi676+NiLYTb4BV8EPaIi3im5s1Ik++v/I8/d29wzSFcJhy
    jJbI/2QrsU37m/0bQ78OHmFsTafEC0Z+BOyxVN37yITczsxOe89mVAKRmE/HFNxcqHDzxl
    67gg2GFIC+hMeJLIAr1k5MttMM9F+tHfQQlea2zOT38KBSxyqN7SfvBKf/XKOQGkdxXcLp
    4riKsXKRb1s6itQdnTNPjXI7+6ztdxpC4Qm7HJHo9y1P9CNY26T2u701VlLspu5tOcv4En
    9KBiVF8SXF6dllqENTmej0r27pYfHK+9l2ZLEJZDd6Yb4c1EsHSn0x0aLAck7d4N2XtsQZ
    sqfRe7AkMPJdLMHnzXFvTiRT8HfVEqT5S0gYp9f6gJ0E6k4JKF7ShWwDiRvDvWjzlh6XiH
    uXg0r+4jTg6ztVRgSGVrhZ+bDoylIpdHguxibCVnrfnprc3SHciRwYaOlvZGip+V8CNS38
    y8XaDbc0n5/RoewPR6XVcXLhBRYu+IRJLTWprrH+ohn0D3astrTkMH7Wy5FaIUB9W8jbAL
    o3g46leBSXa6MN5RdmXIes5mgxlV0O/Gi5Lm2BBhcHYfhwjjeo+HMf4AjpDrN3DxOHT93a
    UAAAdQeU00U3lNNFMAAAAHc3NoLXJzYQAAAgEA4hpQ0d5U+rvOMlQZIhRvBl4YgPm5e8Sd
    AIlGvtXvIYwg0x97ITZ8RUxpJXHz7R43JbiSR0orvtGMi676+NiLYTb4BV8EPaIi3im5s1
    Ik++v/I8/d29wzSFcJhyjJbI/2QrsU37m/0bQ78OHmFsTafEC0Z+BOyxVN37yITczsxOe8
    9mVAKRmE/HFNxcqHDzxl67gg2GFIC+hMeJLIAr1k5MttMM9F+tHfQQlea2zOT38KBSxyqN
    7SfvBKf/XKOQGkdxXcLp4riKsXKRb1s6itQdnTNPjXI7+6ztdxpC4Qm7HJHo9y1P9CNY26
    T2u701VlLspu5tOcv4En9KBiVF8SXF6dllqENTmej0r27pYfHK+9l2ZLEJZDd6Yb4c1EsH
    Sn0x0aLAck7d4N2XtsQZsqfRe7AkMPJdLMHnzXFvTiRT8HfVEqT5S0gYp9f6gJ0E6k4JKF
    7ShWwDiRvDvWjzlh6XiHuXg0r+4jTg6ztVRgSGVrhZ+bDoylIpdHguxibCVnrfnprc3SHc
    iRwYaOlvZGip+V8CNS38y8XaDbc0n5/RoewPR6XVcXLhBRYu+IRJLTWprrH+ohn0D3astr
    TkMH7Wy5FaIUB9W8jbALo3g46leBSXa6MN5RdmXIes5mgxlV0O/Gi5Lm2BBhcHYfhwjjeo
    +HMf4AjpDrN3DxOHT93aUAAAADAQABAAACAB4MdMa7d0w+RtxJ8HAmyo2MVlHXvmacPehb
    Fh+ZE3eAJcGhKq5CjTfxfHzZPNt7u0UEV05ppVAuDbFnrxuAvd9M3J/sHYZqZJtlbLRP+7
    HOTqFuB/Rm+prH1HCVw1Ut+cKrFc5Y440FWLz97KQEg+vk9oTimt4jBe8w4WWDkUjm6mZN
    lP4RUerxzO33KUVlV79AwH65SQeqFvWkPjgc/wpoHaoRteFsYHEGg3mf43hNsCF5Y4CdYl
    iz6xa/7eDvHrIj4dgBNdRrNoADuOIoTeRVRFxDIOZznepM2CHDbHogodOxqUd06BHxdLwG
    25atv+18wknjgC60RcDdSswfOXN0rrXjk7NiyddYs4mcEUrndn89+WUJ18AHLGQxYtl804
    rNMxB4//5GJ9om9Y6A4pUxmOO9ALcnRTuwcQBVSSpQLpYKVk5Q/fgkjaVMAiP0vrvUqVCb
    4xoP1MhxlX6rUM2/CuZExc65VNT9TQYS9PTJM3i5aMvNB36VIhY3bDf3G8Ewd8DIv/3ijU
    mqZKN6VrGOgCAed9RXzsMU0GS1zR+wL8njSYongBt6TmnSpktp7XK+IZhvp4gp6Q3gZVYc
    bYYKAJlfyZDiBhoM4Nu7wKXhPq97F+sc9JmGIvcEJgkS7KVfmRcgNgsnsdi//++atOlv45
    u4JiehtVGq8SMnwwNJAAABAQCFvWha5syz5s3/dhG7Dax+Y+5j9r3Q38dLXfSdTgjn7Bd1
    oelnsmuMGK0NxRf43O+WS7GATcwUDmjB1ICi4PGrgL9FMKFfTi0Orsb/NjiJfyRprlanLA
    En2r7YctcRYhg/C3RKjEstvGIk+miV54A3kspfifqBhqFUA0Bv8WdYe2UnEFocUjUUuMFq
    uQSfJzA5uyqG8gg4y7bNvUHUvSihTYheWIFBYFwE8wg6pyo/C7ioMKOj2T0Wb1oq2gVn6+
    zvgqnCpeVrpSPrfxaaSrwPj7h3vO9sBEaUZdshZl/501xere4VJTH9Tc5ZeZjx83LtFENF
    rdYfNzNQlWr2qDnlAAABAQD7KFcgU7cfxACSbx0eGfcaxfsUcb1EgdGocyw+q2b7upm9e+
    m4ZX0if40Jo7wd2HTFsusGSh1AS80rsFOjk2gKUDNisGXaVvWx+30G3cysmITxfUVQOOUf
    dF13Q5U8wA6SAtP6PonuGcSZtQBSXWyPA9rEWRvA6AAR8K96+X5UVAOB3DNjGBzrEMbJIV
    iG21w3JlvMS6uTvZ1n5+0w/aolYOenvht/j0380h28IS6bxK+RAQewRuR+4tQDwN6hU5BL
    Ml+fLI9d2MIMY+C85ap6CYuWurEnBHVqvKM98MkGFBa8dX5A4Y8BSDdiwcwY3vboP1MKRi
    i08jV/DFGyves9AAABAQDmdk9zZiRd0R5cJ19wKRgvqXyxxE8/tzuMeLGB5misrajOt8Yb
    vQeMOR4t2feGtXFEkyaa+xibMKS99rDo2QM296qL5DaYTHNeXAZqqmjg2MeLzuntTWRiZt
    mu6AuTji6z22z8VspjMNFW5ZSNSxNxdsyf2uZnnqqYqN8rlxuOaJQ4QhzLemMUGFQ2WGLv
    EInR3kKavCQ4yUoZiBYz2umgc86sFDVKSve3rbxexmVei2HXk9N8EaeLaV7Ak3GV+RlJCk
    g4NX6yZU+H2lOxCLTi9HB/sIuDbobCpIYBKc6mqugNfV5+QizyDw/qisN6rPFhhETcyoTI
    tv0aKPih3oKJAAAAFGFiZGVsYXppekBnaXRodWIuY29tAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"