apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  annotations:
    # Tell AIU which image to track
    argocd-image-updater.argoproj.io/image-list: myapp=579385932895.dkr.ecr.us-east-1.amazonaws.com/my-repo
    # Update strategy - 'latest' will pick the newest tag
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 579385932895.dkr.ecr.us-east-1.amazonaws.com/my-repo:2