apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=579385932895.dkr.ecr.us-east-1.amazonaws.com/my-repo
spec:
  project: default
  source:
    repoURL: 'https://github.com/<your-repo>'
    targetRevision: HEAD
    path: path/to/deployment
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
